# Generated by Django 4.0.3 on 2022-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='loja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='parcela',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='valor',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Valor'),
        ),
    ]
