# Generated by Django 4.0.3 on 2022-03-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_compras_data_pagamento_alter_compras_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='data',
            new_name='data_compra',
        ),
    ]
