# Generated by Django 4.0.3 on 2022-03-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_rename_data_compras_data_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='data_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Compra'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
