# Generated by Django 4.0.3 on 2022-07-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0004_alter_compras_data_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
            ],
            options={
                'verbose_name': 'Data de Pagamento',
                'verbose_name_plural': 'Datas de Pagamento',
            },
        ),
    ]
